version: '3.3'
services:
  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - '8069:8069'
      - '8072'
    volumes:
      - 'odoo-data:/var/lib/odoo'
      - './config:/etc/odoo'
      - './addons:/mnt'
      - './addons/extra-addons:/mnt/extra-addons'
    networks:
      - default
      - nginx-net
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 150m
    environment:
      - VIRTUAL_PORT=8069
      - VIRTUAL_HOST=example.com,www.example.com
      - LETSENCRYPT_HOST=example.com,www.example.com
      - LETSENCRYPT_EMAIL=ex@ample.com
  db:
    image: 'postgres:10'
    restart: always
    ports:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGPASS=POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'
    networks:
      - default
    logging:
      driver: json-file
      options:
        max-size: 20m
volumes:
  postgres-data: null
  odoo-data: null
networks:
  nginx-net:
    external: true